# config.yaml
port: 4000
env: production

db:
  dsn: postgres://greenlight:pa55word@db-primary:5432/greenlight?sslmode=disable
  replicas:
    - postgres://greenlight:pa55word@db-replica-1:5432/greenlight?sslmode=disable
  max_open_conns: 500
  max_idle_conns: 500
  max_idle_time: 15m

limiter:
  rps: 10
  burst: 10
  enabled: false

smtp:
  host: smtp.mailtrap.io
  port: 25
  username: "882137d06e7d98"
  password: "0efa52b51f92cb"
  sender: "Greenlight <no-reply@greenlight.alexedwards.net>"

cors:
  trusted_origins: []

jwt:
  secret: "your-very-secure-secret-key"
  expiration: 24h

redis:
  addr: "redis:6379"
  password: ""
  db: 0
  pool_size: 500
  min_idle_conns: 50
  dial_timeout: "3s"
  read_timeout: "1s"
  write_timeout: "1s"
  cache_ttl: "5m"